Image_Processing_Practice/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('image_processor.urls', namespace='image_processor')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

image_processor/urls.py
from django.urls import path
from .views import ImageProcessView, ImageDisplayView

app_name = 'image_processor'

urlpatterns = [
    path('', ImageProcessView.as_view(), name='upload_and_process'),
    path('display/<int:pk>/', ImageDisplayView.as_view(), name='display_image'),
]

image_processor/models.py
from django.db import models


class UploadedImage(models.Model):
    image = models.ImageField(upload_to='images/')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    processed_image = models.ImageField(upload_to='processed/', blank=True, null=True)
    filter_effect = models.CharField(max_length=50, choices=[
        ('gaussian', 'Gaussian Blur'),
        ('box', 'Box Blur'),
        ('unsharp', 'Unsharp Mask'),
        ('median', 'Median Filter'),
        ('min', 'Min Filter'),
        ('max', 'Max Filter')
    ], default='gaussian')

image_processor/forms.py
from django import forms
from .models import UploadedImage


class ImageUploadForm(forms.ModelForm):
    class Meta:
        model = UploadedImage
        fields = ['image']


class ImageProcessForm(forms.ModelForm):
    FILTER_CHOICES = [
        ('gaussian', 'Gaussian Blur'),
        ('box', 'Box Blur'),
        ('unsharp', 'Unsharp Mask'),
        ('median', 'Median Filter'),
        ('min', 'Min Filter'),
        ('max', 'Max Filter')
    ]

    filter_effect = forms.ChoiceField(choices=FILTER_CHOICES, required=True)

    class Meta:
        model = UploadedImage
        fields = ['image']

image_processor/views.py
from django.shortcuts import redirect
from django.views.generic.edit import FormView
from django.views.generic import TemplateView
from .models import UploadedImage
from .forms import ImageUploadForm, ImageProcessForm
from PIL import Image, ImageFilter
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile


class ImageProcessView(FormView):
    form_class = ImageUploadForm
    template_name = 'index.html'

    def form_valid(self, form):
        uploaded_image = form.save()
        filter_effect = self.request.POST.get('filter_effect')

        # Validation to ensure filter_effect is a valid choice
        filter_effects = {
            'gaussian': ImageFilter.GaussianBlur(2),
            'box': ImageFilter.BoxBlur(2),
            'unsharp': ImageFilter.UnsharpMask(radius=2, percent=150, threshold=3),
            'median': ImageFilter.MedianFilter(size=3),
            'min': ImageFilter.MinFilter(size=3),
            'max': ImageFilter.MaxFilter(size=3),
        }

        filter_function = filter_effects.get(filter_effect)

        if filter_function:
            img = Image.open(uploaded_image.image.path)
            processed_img = img.filter(filter_function)

            # Save the processed image
            buffer = BytesIO()
            processed_img.save(buffer, format='JPEG')

            processed_image = InMemoryUploadedFile(
                buffer,
                None,
                'processed.jpg',
                'image/jpeg',
                buffer.tell(),
                None
            )

            uploaded_image.processed_image = processed_image
            uploaded_image.filter_effect = filter_effect
            uploaded_image.save()

            return redirect('image_processor:display_image', pk=uploaded_image.pk)


class ImageDisplayView(TemplateView):
    template_name = 'display.html'
    form_class = ImageProcessForm

    def get(self, request, *args, **kwargs):
        image_id = self.kwargs['pk']
        uploaded_image = UploadedImage.objects.get(pk=image_id)
        form = self.form_class(instance=uploaded_image)
        context = {
            "form": form
        }
        return self.render_to_response(context)

image_processor/templates/display.html
{% extends "base.html" %}

{% block title %}Processed Image{% endblock %}

{% block content %}
    <div style="display: flex; align-items: center; justify-content: center; flex-direction: column;">
        <h1>Processed Image</h1>
        <a href="{% url 'image_processor:upload_and_process' %}" class="btn btn-primary">Back to Main Page</a>
        <hr>
        <img style="width: 80vw; height: 80vh" src="{{ form.instance.processed_image.url }}" alt="Processed Image">



    </div>
{% endblock %}

image_processor/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Main Page{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data" class="mt-4">
        {% csrf_token %}
        <div class="form-group">
            {{ form.image.label_tag }}
            {{ form.image }}
        </div>

        <div class="form-group">
            <label for="filter_effect">Choose Filter Effect:</label>
            <select name="filter_effect" id="filter_effect" class="form-control">
                <option value="gaussian">Gaussian Blur</option>
                <option value="box">Box Blur</option>
                <option value="unsharp">Unsharp Mask</option>
                <option value="median">Median Filter</option>
                <option value="min">Min Filter</option>
                <option value="max">Max Filter</option>
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Upload and Process</button>
    </form>

    <!-- Display selected image -->
    <div class="mt-4" id="selected-image-container" style="display: none;">
        <h2>Selected Image</h2>
        <img id="selected-image" class="img-fluid" alt="Selected Image">
    </div>


    <script src="{% static 'js/image_upload_for_main.js' %}"></script>
{% endblock %}

image_processor/templates/main.html
{% extends "index.html" %}
{% load static %}

{% block title %}Main Page{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data" class="mt-4">
        {% csrf_token %}
        <div class="form-group">
            {{ form.image.label_tag }}
            {{ form.image }}
        </div>

        <div class="form-group">
            <label for="filter_effect">Choose Filter Effect:</label>
            <select name="filter_effect" id="filter_effect" class="form-control">
                <option value="gaussian">Gaussian Blur</option>
                <option value="box">Box Blur</option>
                <option value="unsharp">Unsharp Mask</option>
                <option value="median">Median Filter</option>
                <option value="min">Min Filter</option>
                <option value="max">Max Filter</option>
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Upload and Process</button>
    </form>

    <!-- Display selected image -->
    <div class="mt-4" id="selected-image-container" style="display: none;">
        <h2>Selected Image</h2>
        <img id="selected-image" class="img-fluid" alt="Selected Image">
    </div>

    <script src="{% static 'js/image_upload_for_main.js' %}"></script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Image Processing{% endblock %}</title>
    <!-- Add Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body style="background-color: lightgray">
    <div class="container mt-5">
        <h1 class="text-center">{% block header %}Image Processing App{% endblock %}</h1>
        <hr>
        {% block content %}{% endblock %}
    </div>

    <!-- Add Bootstrap JS (optional) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Image Processing{% endblock %}</title>
    <!-- Add Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body style="background-color: lightgray">
    <div class="container mt-5">
        <h1 class="text-center">{% block header %}Image Processing App{% endblock %}</h1>
        <hr>
        {% block content %}{% endblock %}
    </div>

    <!-- Add Bootstrap JS (optional) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>